# This is a basic workflow to help you get started with Actions

name: Publish google collab notebook

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: ['master']

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  updateBranch:
  name: Update collab branch
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@master
  - uses: Embraser01/update-git-branch-action@v1.0.0
    if: github.ref == 'refs/heads/master'
    with:
      branch: staging
      force: 1 # To push-force to the branch
      githubToken: ${{ secrets.PAT_TOKEN }} # Github Token

